**NumPy_Lab_Practice_Questions**

In [3]:
# Create a NumPy array from [10, 20, 30, 40, 50]. Display shape, size, and data type.
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Array:", arr)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data type:", arr.dtype)

Array: [10 20 30 40 50]
Shape: (5,)
Size: 5
Data type: int64


In [4]:
# Create a 3 × 4 array containing numbers from 1 to 12.
import numpy as np
arr = np.arange(1, 13).reshape(3, 4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
# Create an array of zeros, ones, and an identity matrix.
zeros = np.zeros((3, 3))
ones = np.ones((3, 3))
identity = np.eye(3)

print("Zeros:")
print(zeros)

print("\nOnes:")
print(ones)

print("\nIdentity Matrix:")
print(identity)

Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
# Generate all even numbers between 10 and 50 using np.arange().
even_numbers = np.arange(10, 51, 2)
print(even_numbers)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [7]:
# Create 10 equally spaced numbers between 0 and 1 using np.linspace().
arr = np.linspace(0, 1, 10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [8]:
# Given two arrays, perform element-wise addition, subtraction, multiplication, and division.
a = np.array([10, 20, 30, 40])
b = np.array([2, 4, 5, 8])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [12 24 35 48]
Subtraction: [ 8 16 25 32]
Multiplication: [ 20  80 150 320]
Division: [5. 5. 6. 5.]


In [9]:
# Calculate square and cube of every element.
arr = np.array([1, 2, 3, 4, 5])

print("Square:", arr ** 2)
print("Cube:", arr ** 3)

Square: [ 1  4  9 16 25]
Cube: [  1   8  27  64 125]


In [10]:
# Increase every element by 15%.
arr = np.array([10, 20, 30, 40, 50])

print("Original array:", arr)
print("Array after increasing by 15%:", arr * 1.15)

Original array: [10 20 30 40 50]
Array after increasing by 15%: [11.5 23.  34.5 46.  57.5]


In [11]:
# Find element-wise maximum and minimum.
a = np.array([10, 50, 30, 80])
b = np.array([20, 40, 60, 70])

print("Maximum:", np.maximum(a, b))
print("Minimum:", np.minimum(a, b))

Maximum: [20 50 60 80]
Minimum: [10 40 30 70]


In [12]:
# Create an array from 0 to 20 and extract:
arr = np.arange(21)
print("Array:", arr)
print("First five:", arr[:5])
print("Last five:", arr[-5:])
print("Index 5 to 15:", arr[5:16])
print("Every second element:", arr[::2])

Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
First five: [0 1 2 3 4]
Last five: [16 17 18 19 20]
Index 5 to 15: [ 5  6  7  8  9 10 11 12 13 14 15]
Every second element: [ 0  2  4  6  8 10 12 14 16 18 20]


In [13]:
# Replace the first five elements with 100.
arr = np.arange(10)
arr[:5] = 100
print(arr)

[100 100 100 100 100   5   6   7   8   9]


In [14]:
# Create an array and demonstrate the difference between a slice/view and a copy
arr = np.array([10, 20, 30, 40, 50])

view = arr[1:4]
view[0] = 999

print("Original after modifying view:")
print(arr)

arr2 = np.array([10, 20, 30, 40, 50])

copy_arr = arr2[1:4].copy()
copy_arr[0] = 999

print("Original after modifying copy:")
print(arr2)

Original after modifying view:
[ 10 999  30  40  50]
Original after modifying copy:
[10 20 30 40 50]


In [15]:
# Reverse a NumPy array using slicing.
arr = np.array([1, 2, 3, 4, 5])
reverse = arr[::-1]
print(reverse)

[5 4 3 2 1]


In [16]:
# Create the matrix [[10,20,30],[40,50,60],[70,80,90]]. Extract the second row, third column, and element 50.
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Second row:", matrix[1])
print("Third column:", matrix[:, 2])
print("Element 50:", matrix[1, 1])

Second row: [40 50 60]
Third column: [30 60 90]
Element 50: 50


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [17]:
# Extract [[20,30],[50,60]].
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

sub_matrix = matrix[:2, 1:]

print(sub_matrix)

[[20 30]
 [50 60]]


In [18]:
# Create a 5 × 5 matrix containing 1–25 and extract required elements.
matrix = np.arange(1, 26).reshape(5, 5)

print("Matrix:")
print(matrix)

print("First row:")
print(matrix[0])

print("Last column:")
print(matrix[:, -1])

print("Middle element:")
print(matrix[2, 2])

print("Top-left 3x3:")
print(matrix[:3, :3])

Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
First row:
[1 2 3 4 5]
Last column:
[ 5 10 15 20 25]
Middle element:
13
Top-left 3x3:
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


In [19]:
# Create an array containing 1–12 and reshape into 3 × 4.
arr = np.arange(1, 13)
matrix = arr.reshape(3, 4)
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
# Reshape a 1-D array into a 2 × 5 matrix.
arr = np.arange(1, 11)
matrix = arr.reshape(2, 5)
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [21]:
# Convert a 3 × 4 matrix into a 4 × 3 matrix using transpose.
matrix = np.arange(1, 13).reshape(3, 4)

transposed = matrix.transpose()

print("Original:")
print(matrix)

print("Transposed:")
print(transposed)

Original:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Transposed:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [22]:
# Use transpose() and swapaxes() on a 3-D array.
arr = np.arange(24).reshape(2, 3, 4)
print("Original shape:", arr.shape)
transpose_arr = arr.transpose(2, 1, 0)
print("Transpose shape:", transpose_arr.shape)
swap_arr = arr.swapaxes(0, 2)
print("Swapaxes shape:", swap_arr.shape)

Original shape: (2, 3, 4)
Transpose shape: (4, 3, 2)
Swapaxes shape: (4, 3, 2)


In [23]:
# Create two 3 × 3 matrices and perform element-wise addition and multiplication.
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

print("Addition:")
print(A + B)

print("Element-wise multiplication:")
print(A * B)

Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]
Element-wise multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [24]:
# Calculate matrix product using np.dot().
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

result = np.dot(A, B)
print(result)

[[19 22]
 [43 50]]


In [25]:
# Find transpose and dot product with original matrix.
A = np.array([
    [1, 2],
    [3, 4]
])

transpose = A.T

result = np.dot(transpose, A)

print("Transpose:")
print(transpose)

print("Transpose dot Original:")
print(result)

Transpose:
[[1 3]
 [2 4]]
Transpose dot Original:
[[10 14]
 [14 20]]


In [26]:
# Calculate square root of every element.
arr = np.array([1, 4, 9, 16, 25])
result = np.sqrt(arr)
print(result)

[1. 2. 3. 4. 5.]


In [27]:
# Calculate e^x for every element.
arr = np.array([0, 1, 2, 3])
result = np.exp(arr)
print(result)

[ 1.          2.71828183  7.3890561  20.08553692]


In [28]:
# Generate a random array and calculate square root, exponential, and absolute values.
arr = np.random.randn(5)

print("Random array:")
print(arr)

print("Square root of absolute values:")
print(np.sqrt(np.abs(arr)))

print("Exponential:")
print(np.exp(arr))

print("Absolute values:")
print(np.abs(arr))

Random array:
[ 0.79374966  0.1405879  -0.52369201  1.44746728  1.13159541]
Square root of absolute values:
[0.8909263  0.37495053 0.72366567 1.20310735 1.06376473]
Exponential:
[2.21167393 1.15095025 0.59232962 4.25233092 3.10059927]
Absolute values:
[0.79374966 0.1405879  0.52369201 1.44746728 1.13159541]


In [29]:
# Generate two random arrays and find element-wise maximum.
a = np.random.rand(5)
b = np.random.rand(5)

print("Array A:", a)
print("Array B:", b)

maximum = np.maximum(a, b)

print("Element-wise maximum:", maximum)

Array A: [0.01819603 0.5656613  0.2615065  0.34466427 0.10390394]
Array B: [0.25687737 0.80434847 0.42073326 0.91026122 0.83708943]
Element-wise maximum: [0.25687737 0.80434847 0.42073326 0.91026122 0.83708943]


In [30]:
# Replace marks below 40 with 0.
marks = np.array([35, 72, 48, 90, 55, 28])
result = np.where(marks < 40, 0, marks)
print(result)

[ 0 72 48 90 55  0]


In [31]:
# Classify income as High if ≥ 50,000, otherwise Low.
income = np.array([30000, 55000, 45000, 80000, 60000])

classification = np.where(
    income >= 50000,
    "High",
    "Low"
)

print(classification)

['Low' 'High' 'Low' 'High' 'High']


In [32]:
# Replace values greater than 30 with 100.
arr = np.array([10, 25, 35, 40, 20, 50])
result = np.where(arr > 30, 100, arr)
print(result)

[ 10  25 100 100  20 100]


In [33]:
# Calculate total sum, mean, variance, and standard deviation.
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Sum:", np.sum(matrix))
print("Mean:", np.mean(matrix))
print("Variance:", np.var(matrix))
print("Standard deviation:", np.std(matrix))

Sum: 450
Mean: 50.0
Variance: 666.6666666666666
Standard deviation: 25.81988897471611


In [34]:
# Calculate row-wise and column-wise sums.
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

row_sum = np.sum(matrix, axis=1)
column_sum = np.sum(matrix, axis=0)

print("Row-wise sum:", row_sum)
print("Column-wise sum:", column_sum)

Row-wise sum: [ 6 15 24]
Column-wise sum: [12 15 18]


In [35]:
# Given marks of 10 students, calculate mean, standard deviation, minimum, and maximum.
marks = np.array([65, 78, 55, 90, 45, 88, 72, 60, 95, 50])

print("Mean:", np.mean(marks))
print("Standard deviation:", np.std(marks))
print("Minimum:", np.min(marks))
print("Maximum:", np.max(marks))

Mean: 69.8
Standard deviation: 16.70808187674456
Minimum: 45
Maximum: 95


In [36]:
# Demonstrate any() and all().
arr = np.array([True, True, False, True])

print("Any:", np.any(arr))
print("All:", np.all(arr))

Any: True
All: False


In [37]:
# Generate 10 random numbers and sort them.
arr = np.random.randint(1, 100, 10)

print("Original:")
print(arr)

print("Sorted:")
print(np.sort(arr))

Original:
[66 18  5 43 22  6 24 34  7 58]
Sorted:
[ 5  6  7 18 22 24 34 43 58 66]


In [38]:
# Find unique elements from an array containing repeated values.
arr = np.array([1, 2, 2, 3, 4, 4, 5, 5, 5])
unique_values = np.unique(arr)
print(unique_values)

[1 2 3 4 5]


In [39]:
# Find unique student marks.
marks = np.array([65, 78, 55, 90, 45, 88, 72, 60, 95, 50])
unique_marks = np.unique(marks)
print(unique_marks)

[45 50 55 60 65 72 78 88 90 95]


In [40]:
# Use np.in1d() to check selected values.
arr = np.array([10, 20, 30, 40, 50])
selected = np.array([20, 40, 60])

result = np.in1d(selected, arr)
print(result)

[ True  True False]


/tmp/ipykernel_2712/3252329930.py:5: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  result = np.in1d(selected, arr)


In [41]:
# Student Marks Analysis. Create marks for 10 students in 3 subjects. Calculate total, average, and identify students whose average ≥ 50.
marks = np.array([
    [60, 70, 80],
    [45, 55, 65],
    [30, 40, 35],
    [80, 75, 90],
    [50, 60, 55],
    [35, 45, 40],
    [90, 85, 95],
    [55, 50, 60],
    [40, 35, 45],
    [70, 65, 75]
])

total = np.sum(marks, axis=1)
average = np.mean(marks, axis=1)

print("Total marks:")
print(total)

print("Average marks:")
print(average)

students = np.where(average >= 50)[0]

print("Students whose average is >= 50:")
print(students + 1)


Total marks:
[210 165 105 245 165 120 270 165 120 210]
Average marks:
[70.         55.         35.         81.66666667 55.         40.
 90.         55.         40.         70.        ]
Students whose average is >= 50:
[ 1  2  4  5  7  8 10]


In [42]:
# Matrix Analysis. Create a 4 × 4 matrix containing 1–16. Find transpose, row sums, column sums, mean, maximum, minimum, and central 2 × 2 matrix.
matrix = np.arange(1, 17).reshape(4, 4)

print("Matrix:")
print(matrix)

print("\nTranspose:")
print(matrix.T)

print("\nRow-wise sums:")
print(np.sum(matrix, axis=1))

print("\nColumn-wise sums:")
print(np.sum(matrix, axis=0))

print("\nMean:")
print(np.mean(matrix))

print("\nMaximum:")
print(np.max(matrix))

print("\nMinimum:")
print(np.min(matrix))

print("\nCentral 2x2 matrix:")
print(matrix[1:3, 1:3])

Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Transpose:
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

Row-wise sums:
[10 26 42 58]

Column-wise sums:
[28 32 36 40]

Mean:
8.5

Maximum:
16

Minimum:
1

Central 2x2 matrix:
[[ 6  7]
 [10 11]]


In [43]:
# Random Data Analysis. Generate 20 observations using np.random.randn(). Calculate mean, standard deviation, minimum, maximum, sorted values, and replace negative values with zero.
data = np.random.randn(20)

print("Original data:")
print(data)

print("\nMean:")
print(np.mean(data))

print("\nStandard deviation:")
print(np.std(data))

print("\nMinimum:")
print(np.min(data))

print("\nMaximum:")
print(np.max(data))

print("\nSorted values:")
print(np.sort(data))

result = np.where(data < 0, 0, data)

print("\nNegative values replaced with zero:")
print(result)

Original data:
[-0.40359804  1.33232729 -0.65850472 -0.9274775  -0.06803649  0.1577623
  0.2881794   0.62179884  0.52175601 -0.38253846 -1.19956311 -1.29151369
 -0.50463385 -0.84394014 -0.3020044  -0.34804214 -0.22331834 -0.4594487
  1.28111095  0.59651461]

Mean:
-0.1406585083138219

Standard deviation:
0.7175697455378821

Minimum:
-1.2915136880850782

Maximum:
1.3323272901373766

Sorted values:
[-1.29151369 -1.19956311 -0.9274775  -0.84394014 -0.65850472 -0.50463385
 -0.4594487  -0.40359804 -0.38253846 -0.34804214 -0.3020044  -0.22331834
 -0.06803649  0.1577623   0.2881794   0.52175601  0.59651461  0.62179884
  1.28111095  1.33232729]

Negative values replaced with zero:
[0.         1.33232729 0.         0.         0.         0.1577623
 0.2881794  0.62179884 0.52175601 0.         0.         0.
 0.         0.         0.         0.         0.         0.
 1.28111095 0.59651461]


In [44]:
# Matrix Operations Challenge. Create two 3 × 3 matrices and perform:
# element-wise addition
# element-wise multiplication
# matrix multiplication
# transpose of first matrix
# maximum/minimum of resulting matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

# Element-wise addition
addition = A + B

# Element-wise multiplication
multiplication = A * B

# Matrix multiplication
matrix_product = np.dot(A, B)

# Transpose of A
transpose_A = A.T

# Maximum and minimum of resulting matrix
maximum = np.max(matrix_product)
minimum = np.min(matrix_product)

print("Element-wise addition:")
print(addition)

print("\nElement-wise multiplication:")
print(multiplication)

print("\nMatrix multiplication:")
print(matrix_product)

print("\nTranspose of A:")
print(transpose_A)

print("\nMaximum of resulting matrix:")
print(maximum)

print("\nMinimum of resulting matrix:")
print(minimum)

Element-wise addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Element-wise multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Matrix multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Transpose of A:
[[1 4 7]
 [2 5 8]
 [3 6 9]]

Maximum of resulting matrix:
138

Minimum of resulting matrix:
18


In [45]:
# Array Manipulation Challenge. Create an array containing 1–24, reshape to 4 × 6, extract selected rows and columns, transpose it, calculate row/column statistics, and identify unique values.
arr = np.arange(1, 25)

matrix = arr.reshape(4, 6)

print("4x6 Matrix:")
print(matrix)

# Selected rows
print("\nFirst and third rows:")
print(matrix[[0, 2]])

# Selected columns
print("\nSecond and fourth columns:")
print(matrix[:, [1, 3]])

# Transpose
print("\nTranspose:")
print(matrix.T)

# Row statistics
print("\nRow sums:")
print(np.sum(matrix, axis=1))

print("\nRow means:")
print(np.mean(matrix, axis=1))

# Column statistics
print("\nColumn sums:")
print(np.sum(matrix, axis=0))

print("\nColumn means:")
print(np.mean(matrix, axis=0))

# Unique values
print("\nUnique values:")
print(np.unique(matrix))

4x6 Matrix:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

First and third rows:
[[ 1  2  3  4  5  6]
 [13 14 15 16 17 18]]

Second and fourth columns:
[[ 2  4]
 [ 8 10]
 [14 16]
 [20 22]]

Transpose:
[[ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]
 [ 6 12 18 24]]

Row sums:
[ 21  57  93 129]

Row means:
[ 3.5  9.5 15.5 21.5]

Column sums:
[40 44 48 52 56 60]

Column means:
[10. 11. 12. 13. 14. 15.]

Unique values:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
